import { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
    return knex.raw(`
    CREATE TABLE departments (
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      department_name text NOT NULL
    )
  `);
}


export async function down(knex: Knex): Promise<void> {
    return knex.raw(`
    DROP TABLE departments
  `);
}

